gfx/env/LostcityBk.tga
gfx/env/LostcityDn.tga
gfx/env/LostcityFt.tga
gfx/env/LostcityLf.tga
gfx/env/LostcityRt.tga
gfx/env/LostcityUp.tga
models/zs_lostcity/big_tree01.mdl
models/zs_lostcity/car_scrapped.mdl
models/zs_lostcity/crane01.mdl
sprites/zs_lostcity/blueflare1.spr
zs_light_zombie_boss_btm.wad
models/CSO_Lightzombie/camera.mdl
models/CSO_Lightzombie/ef_tentacle.mdl
models/CSO_Lightzombie/ef_tentacle_sign.mdl
models/CSO_Lightzombie/lightzombieboss.mdl
models/CSO_Lightzombie/lightzombieboss_bomb.mdl
sprites/CSO_Lightzombie/LightZombie_Boss_HP.spr
sound/CSO_LightZombie/appear.wav
sound/CSO_LightZombie/zbs_attack1.wav
sound/CSO_LightZombie/zbs_bomb_nuke.wav
sound/CSO_LightZombie/death.wav
sound/CSO_LightZombie/Round_boss/Scenario_Ready.mp3
sound/CSO_LightZombie/Round_boss/Scenario_Fight_v2.mp3
