; Map Manager Modular 3.2.0 - G3B LITE
; Orden importante: Core primero, Scheduler antes de RTV/Nomination/Informer.

map_manager_core.amxx
map_manager_scheduler.amxx
map_manager_rtv.amxx
map_manager_nomination.amxx
map_manager_informer.amxx
